name: CI/CD Frontend

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t igrowker/i004-mindup-front:${{ github.sha }} .
          docker tag igrowker/i004-mindup-front:${{ github.sha }} igrowker/i004-mindup-front:latest
          docker push igrowker/i004-mindup-front:${{ github.sha }}
          docker push igrowker/i004-mindup-front:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: [self-hosted, frontend-deploy]

    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > mindup.pem
          chmod 600 mindup.pem

      - name: Deploy Frontend to EC2
        run: |
          ssh -i mindup.pem -o StrictHostKeyChecking=no admin@${{ secrets.EC2_PUBLIC_IP }} "
            cd /home/admin/frontend &&
            docker pull igrowker/i004-mindup-front:${{ github.sha }} &&
            docker stop mindup-front || true &&
            docker rm mindup-front || true &&
            docker run -d \
              --name mindup-front \
              -p 80:80 \
              -e EC2_PUBLIC_IP=${{ secrets.EC2_PUBLIC_IP }} \
              igrowker/i004-mindup-front:${{ github.sha }} &&
            cd /home/admin &&
            ./run.sh"
