name: CI/CD Frontend

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t igrowker/i004-mindup-front:${{ github.sha }} .
          docker tag igrowker/i004-mindup-front:${{ github.sha }} igrowker/i004-mindup-front:latest
          docker push igrowker/i004-mindup-front:${{ github.sha }}
          docker push igrowker/i004-mindup-front:latest

